name: user_repository
publish_to: none

environment: 
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  uuid: ^4.5.1
  domain_entities: 
    path: ../domain_entities
  key_value_storage:
    path: ../key_value_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
