name: board_game
publish_to: none

environment: 
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  domain_entities:
    path: ../../domain_entities
  provider: ^6.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true